### ISSUE TITLE
settings to allow adjust the position of the readme content

### ISSUE THREAD

**Issue by missedone** [simeji/readme_at_repositories#3]
hi, simeij

this exactly is the plugin i'm looking for, have a quick play around, quite nice.

however, i think it'd be better if we (as the user) can specify the position of the content on the repository page. currently it's on top of the page, i'd like to put it at the bottom, and even nice, if there is a clear separator between repository file list and the readme content (e.g. a horizontal separator, or add border to the readme body)

thanks

**Comment by simeji** [comment]
@missedone I think, I got this features. Can I close this issue?
